---
- hosts: gbm-server
  remote_user: root
  become: yes
  become_method: su
  become_user: gbm

  tasks:
    # download the application
    - name: clone git repository
      git:
        repo: https://github.com/devinit/grand-bargain-monitoring.git
        dest: /home/gbm/grand-bargain-monitoring
        update: yes
        version: dev

    # install requirements
    - name: install pip requirements
      pip:
        requirements: /home/gbm/grand-bargain-monitoring/requirements.txt
        # executable: pip
        virtualenv: /home/gbm/grand-bargain-monitoring/pyenv
        virtualenv_python: python3
        virtualenv_site_packages: no

    # run the app
