---
- hosts: gbm-server
  remote_user: root
  become: yes
  become_method: su
  become_user: gbm

  tasks:
    # download the grand-bargain-monitoring application
    - name: clone grand-bargain-monitoring git repository
      git:
        repo: https://github.com/devinit/grand-bargain-monitoring.git
        dest: /home/gbm/grand-bargain-monitoring
        update: yes
        version: deployment

    # create directory to store remote data in
    - name: create remote data directory
      file:
        path: /home/gbm/grand-bargain-monitoring/data/remote
        state: directory

    # install requirements
    - name: install pip requirements
      pip:
        requirements: /home/gbm/grand-bargain-monitoring/requirements.txt
        virtualenv: /home/gbm/grand-bargain-monitoring/pyenv
        virtualenv_python: python3
        virtualenv_site_packages: no

    # copy apache config file to correct location
    - name: copy apache2 config file
      copy:
        src: /var/www/grand-bargain-monitoring/deployment/apache2.conf
        dest: /etc/apache2/sites-available/000-default.conf
        owner: root
        group: root
        mode: 0644

    # use get_url commands rather than running `src/load_remote_data.py`
    # download remote data
    - name: download summary_stats.csv
      get_url:
        url: http://dashboard.iatistandard.org/summary_stats.csv
        dest: /home/gbm/grand-bargain-monitoring/data/remote/summary_stats.csv
        mode: 0440

    # set up cron job to update remote data on regular basis

    # clone, set-up and configure IATI-Stats fork
    - name: clone devinit/gbm-IATI-Stats git repository
      git:
        repo: https://github.com/devinit/gbm-IATI-Stats.git
        dest: /home/gbm/gbm-IATI-Stats
        update: yes
        version: humanitarian-only

    # clone, set-up and configure IATI-Dashboard fork
    - name: clone devinit/gbm-IATI-Dashboard git repository
      git:
        repo: https://github.com/devinit/gbm-IATI-Dashboard.git
        dest: /home/gbm/gbm-IATI-Dashboard
        update: yes
        version: stop-after-csv-gen

    # run the app
